# Generated by Django 5.1.4 on 2024-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz_data',
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_file',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/'),
        ),
    ]
