# Generated by Django 5.1.4 on 2024-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_quiz_file_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz',
            field=models.JSONField(default=dict),
        ),
    ]
