# Generated by Django 5.1.4 on 2025-05-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_quiz_field_help_text'),
        ('courses', '0005_question_choice_test_question_test_testsubmission_and_more'),
    ]

    operations = [
    ]
