# Generated by Django 5.1.4 on 2025-05-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge_20250515_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Model answer for open-ended questions', null=True),
        ),
    ]
